global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_api'
    metrics_path: '/metrics'  # Caminho onde a API .NET expõe as métricas
    static_configs:
      - targets: ['api:8080']  # Nome do serviço do container da API no Docker Compose
