services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - web-api-contacts
    volumes:
      - redis_data:/data
  api:
    build:
      context: .
      dockerfile: TechChallange.Api/Dockerfile
      args:
       version: 1
    depends_on:
      - redis
    image: api-contacts
    ports:
      - 5193:8080
    networks:
      - web-api-contacts

  prometheus:
    build:
      context: ./TechChallange.Api/prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    depends_on:
      - api
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - web-api-contacts
    volumes:
      - prometheus_data:/prometheus/data:/data

  grafana:
    build:
      context: ./TechChallange.Api/grafana
      dockerfile: Dockerfile
      args:
        version: 1
    depends_on:
      - prometheus
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      - web-api-contacts
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  web-api-contacts:
    driver: bridge

volumes:
  redis_data:
  grafana_data:
  prometheus_data: