{
 "title": "Tech Challange - Fase 2 ",
 "time": { "from": "2025-02-18T00:19:29.679Z", "to": "2025-02-18T00:23:43.114Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_num_threads,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latencia",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{endpoint=~\"api/.*\"}[$__interval]) / rate(http_request_duration_seconds_count{endpoint=~\"api/.*\"}[$__interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requisições por endpoint",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((http_requests_received_total{endpoint=~\"api/.*\"}))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requsições/Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\"api/.*\"})",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Uso de Memoria RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "Memoria RAM"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "CPU (%)" }
   ]
  },
  { "title": "Taxa de transmissão de rede", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 } }
 ]
}