name: Git Actions Tech Challenge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar pacotes
      run: dotnet restore ./TechChallange/TechChallange.sln

    - name: Compilar o código
      run: dotnet build ./TechChallange/TechChallange.sln --no-restore --configuration Release

    - name: Set up Docker
      run: docker info

    - name: Executar testes unitários e de integração
      run: dotnet test ./TechChallange/TechChallange.sln --no-build --configuration Release --logger trx
      env:
        DOTNET_EnablePreviewFeatures: "true"

    - name: Salvar resultados dos testes
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: "**/*.trx"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        if [ -n "$DOCKER_HUB_PASSWORD" ] && [ -n "$DOCKER_HUB_USERNAME" ]; then
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        else
          echo "DOCKER_HUB_USERNAME ou DOCKER_HUB_PASSWORD não estão definidos. Pulando login..."
        fi

    - name: Construção da imagem Docker
      run: docker build -f ./TechChallange/TechChallange.Api/Dockerfile -t vmrsilva/tech-challange:latest -t vmrsilva/tech-challange:${{ github.sha }} .

    - name: Push da imagem para o Docker Hub
      run: |
        if [ -n "${{ secrets.DOCKER_HUB_PASSWORD }}" ] && [ -n "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
          docker push vmrsilva/tech-challange:latest
          docker push vmrsilva/tech-challange:${{ github.sha }}
        else
          echo "DOCKER_HUB_USERNAME ou DOCKER_HUB_PASSWORD não estão definidos. Pulando o push..."
        fi
