name: Run Tests 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./TechChallange/TechChallange.sln

      - name: Build
        run: dotnet build ./TechChallange/TechChallange.sln --no-restore

      - name: Test
        run: dotnet test ./TechChallange/TechChallange.sln --no-build
